"""empty message

Revision ID: 59dbabeb0171
Revises: ba4731475697
Create Date: 2017-10-02 13:57:56.278440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59dbabeb0171'
down_revision = 'ba4731475697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_influencer', sa.Column('followers', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_influencer',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('handle', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('stars', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_user',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('first', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('last', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('company', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('website', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('keyword', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_lead',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.Column('createdBy', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('influencer_id', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], [u'auth_influencer.id'], name=u'auth_lead_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('association',
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('influencer_id', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['influencer_id'], [u'auth_influencer.id'], name=u'association_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'auth_user.id'], name=u'association_ibfk_1'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
